name = "reports-mapking"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "reports.icebergmedia.co.uk/mapking/*", zone_name = "icebergmedia.co.uk" },
  { pattern = "reports.icebergmedia.co.uk/mapking", zone_name = "icebergmedia.co.uk" }
]

[[d1_databases]]
binding = "DB"
database_name = "reports-mapking"
database_id = "d52e3a51-bcb2-4ac3-9fff-0b8c0a8f2185"
